version: "3.8"

services:
  gateway:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: ip-address-gateway
    ports:
      - "8000:8000"
    volumes:
      - ./gateway-service:/var/www/html
    depends_on:
      - auth_service
      - ip_service
    environment:
      - AUTH_SERVICE_URL=http://auth_service:8000
      - IP_SERVICE_URL=http://ip_service:8000
    networks:
      - ip-network

  auth_service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: ip-address-auth-service
    ports:
      - "8001:8000"
    volumes:
      - ./auth-service:/var/www/html
    depends_on:
      - auth-db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=auth-db
      - DB_PORT=3306
      - DB_DATABASE=auth_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - JWT_SECRET=techLintPAss0rd!
    networks:
      - ip-network

  ip_service:
    build:
      context: ./ip-service
      dockerfile: Dockerfile
    container_name: ip-address-management-service
    ports:
      - "8002:8000"
    volumes:
      - ./ip-service:/var/www/html
    depends_on:
      - ip-db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=ip-db
      - DB_PORT=3306
      - DB_DATABASE=ip_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - JWT_SECRET=techLintPAss0rd!
    networks:
      - ip-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ip-address-frontend
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - ip-network
    depends_on:
      - gateway

  auth-db:
    image: mysql:8.0
    container_name: ip-address-auth-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_db
    networks:
      - ip-network
    volumes:
      - auth-db-data:/var/lib/mysql

  ip-db:
    image: mysql:8.0
    container_name: ip-address-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ip_db
    networks:
      - ip-network
    volumes:
      - ip-db-data:/var/lib/mysql

networks:
  ip-network:
    driver: bridge

volumes:
  auth-db-data:
  ip-db-data:
